name: JS

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js v18.x
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install NPM dependencies
      run: npm ci
      working-directory: wp-content/plugins/pet-project-analytics/

    - name: Run lint
      run: npm run lint
      working-directory: wp-content/plugins/pet-project-analytics/
