name: PHP

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-versions: [ '8.2', '8.3' ]

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer

      - name: Validate composer.json and composer.lock
        run: composer validate
        working-directory: wp-content/plugins/pet-project-analytics/

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
        working-directory: wp-content/plugins/pet-project-analytics/

      # TODO: does it work without working directory setting?
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --prefer-dist --no-progress
        working-directory: wp-content/plugins/pet-project-analytics/

      - name: Run PHPUnit
        run: composer run-script test
        working-directory: wp-content/plugins/pet-project-analytics/

      - name: Run PHPCS
        run: composer run-script lint
        working-directory: wp-content/plugins/pet-project-analytics/